package tools.wlgenerator

import com.xenomachina.argparser.ArgParser
import com.xenomachina.argparser.InvalidArgumentException
import com.xenomachina.argparser.default
import util.checkFile
import java.io.File

class GeneratorArguments (parser: ArgParser) {
    val overwrite by parser.flagging(
            "-o", "--overwrite",
            help = "overwrite existing workload file").default(false)


    val mappingFileName:String by parser.storing(
            "-m", "--mapping",
            help = "Input: mapping file generated by matching tool").addValidator {
        if (!checkFile(File(mappingFileName))) {
            throw InvalidArgumentException("Invalid mapping file")
        }
        if (!mappingFileName.endsWith(".json")) {
            throw InvalidArgumentException("mapping file must be a json file (end with .json)")
        }
    }

    val workloadFileName:String by parser.storing(
            "-w", "--workload",
            help = "Output: name of generated workload file").default("workload.json").addValidator {
        if (File(workloadFileName).exists() && !overwrite) {
            throw InvalidArgumentException(File(workloadFileName).absolutePath + " already exists.")
        }
        if (File(workloadFileName).exists() && overwrite) {
            println("Will overwrite workload file")
        }
        if (!workloadFileName.endsWith(".json")) {
            throw InvalidArgumentException("workload file must be a json file (end with .json)")
        }
    }
}
