package tools.requestdistribution

import com.xenomachina.argparser.ArgParser
import com.xenomachina.argparser.InvalidArgumentException
import com.xenomachina.argparser.default
import util.checkFile
import java.io.File

class DistributionArguments (parser: ArgParser) {
    val overwrite by parser.flagging(
            "-o", "--overwrite",
            help = "overwrite existing mapping file").default(false)


    val mappingFileName:String by parser.storing(
            "-m", "--mapping",
            help = "Input: mapping file generated by matching tool").addValidator {
        if (!checkFile(File(mappingFileName))) {
            throw InvalidArgumentException("Invalid mapping file")
        }
        if (!mappingFileName.endsWith(".json")) {
            throw InvalidArgumentException("mapping file must be a json file (end with .json)")
        }
    }
}
